### ISSUE TITLE
Logo and launch screen are needed

### ISSUE THREAD

**Issue by kindraywind** [kindraywind/ThaiTechEventCalendar-iOS#1]

**Comment by zuuritaly** [comment]
Hello @kindraywind 
I'm a graphic designer and I design logos for open source projects. 

Usually I ask the following questions to assist me in the creative process:

Do you have something in your mind for the logo?
Do you want something specific for the logo?
What colors do you want in the logo?

With your answers I will design a logo for your project and if you like it you can keep it and used.

Best Regards

Zuur

**Comment by kindraywind** [comment]
Hello @zuuritaly !
We really appreciate your kindness.
Unfortunately, I've forgotten to close this issue at the time I got the logos from another contributor. 😭 

By the way, I think my fellow would love to finally have a logo for his [networking library](https://github.com/kittinunf/Fuel) 👍
