### ISSUE TITLE
Get rid of the hard-coded strings and magic numbers

### ISSUE THREAD

**Issue by kindraywind** [kindraywind/ThaiTechEventCalendar-iOS#2]

**Comment by PH9** [comment]
I not agree with this issue. We must not track this, we must fix it.
I believe, issue should be more specific.

**Comment by ambas** [comment]
@kindraywind I see a lot of hard code string for resources (eg. storyboard name/ cell identifier) 

Should we use some generated resource tool for it like `R.swift`?

if you are agree with this idea I can try to create a PR for it to propose the idea :)

**Comment by PH9** [comment]
@ambas R.swift take more time to build. But I have no other solution, so I agree with it. 👍
